## Import World Rugby 7s World Series Analysis Reports ##
Import Analysis Reports (Excel) from each stop on the 2018 7s World Series

In [5]:
# You can use pandas' ExcelFile parse method to read Excel sheets, see io docs:
import pandas as pd
xls = pd.ExcelFile('../data/2017-18/2017-18 HSBC SS Cape Town 7s Game Analysis Statistical Output.xlsx')
df = xls.parse('Raw Data', skiprows=6, index_col=None, na_values=['NA'])

In [16]:
df.head(10)
df.columns = ['col1', 'Team', 'Opposition', 'Total PointsScored', 'Total PointsConceded', 'Total TriesScored', 'Total TriesConceded', 'Try Scoring Rate(1 every x secs)', 'Try Conceding Rate(1 every x secs)', 'Tries Scored Build-Up(No Ruck/Maul)', 'Tries Conceded Build-Up(No Ruck/Maul)', 'Opp22m Entries', 'Opp22m Entry Rate(1 every  secs)', 'Own22m Entries', 'Own22m Entry Rate(1 every x secs)', 'Tries Scoredper Opp22m Entry', 'Tries Concededper Own22m Entry', 'Possession Time(Own)', 'Possession Time(Opp)', 'Passes', 'Passing Rate(1 every x secs)', 'Rucks Attack', 'Rucking RateAttack (secs)', 'RucksDefence', '% Ruck SuccessOwn', 'Own RucksWon per Match', '% Ruck SuccessOpp', 'Opp RucksWon per Match', 'TurnoversReceived', 'TurnoversConceded', 'TurnoverDifferential', 'OwnContestable Restarts', 'Own ContestableRestarts Regained', 'OppContestable Restarts', 'Opp ContestableRestarts Received', 'Total ScrumsOwn Feed', 'Scrum SuccessOwn Feed', 'Total LineoutsOwn Throw', 'Lineout SuccessOwn Throw', 'Penalty/FKConceded', 'TRM PenaltyConceded', 'Cards']
df

,col1,Team,Opposition,Total PointsScored,Total PointsConceded,Total TriesScored,Total TriesConceded,Try Scoring Rate(1 every x secs),Try Conceding Rate(1 every x secs),Tries Scored Build-Up(No Ruck/Maul),...,Own ContestableRestarts Regained,OppContestable Restarts,Opp ContestableRestarts Received,Total ScrumsOwn Feed,Scrum SuccessOwn Feed,Total LineoutsOwn Throw,Lineout SuccessOwn Throw,Penalty/FKConceded,TRM PenaltyConceded,Cards
0,NaN,Team,Opposition,Scored,Conceded,Scored,Conceded,(1 every '' secs),(1 every '' secs),(No Ruck/Maul),...,Restarts Regained,Contestable Restarts,Restarts Received,Own Feed,Own Feed,Own Throw,Own Throw,Conceded,Conceded,Cards
1,NaN,Argentina,New Zealand,14,38,2,6,108,36,1,...,1,0,0,0,0,2,1,1,0,0
2,NaN,NaN,Canada,14,12,2,2,97,105,2,...,1,2,2,2,2,2,2,4,3,0
3,NaN,NaN,USA,28,12,4,2,41,133,1,...,2,3,2,1,1,1,1,1,1,0
4,NaN,NaN,Uganda,43,7,7,1,37,178,4,...,5,0,0,0,0,2,2,0,0,0
5,NaN,NaN,England,7,24,1,4,176,57,0,...,0,4,3,3,3,2,0,0,0,0
6,NaN,NaN,Scotland,19,14,3,2,60,95,1,...,1,3,3,2,2,2,2,4,0,0
7,NaN,Average,NaN,20.8,17.8,3.2,2.8,62,76,1.5,...,1.7,2,1.7,1.3,1.3,1.8,1.3,1.7,0.7,0
8,NaN,Australia,Spain,26,7,4,1,58,189,3,...,1,2,1,4,4,2,2,5,4,0
9,NaN,NaN,Wales,42,5,6,1,41,195,3,...,4,1,1,2,2,1,0,3,2,1
10,NaN,NaN,Uganda,47,12,7,2,35,100,4,...,3,2,2,3,3,0,0,0,0,0
11,NaN,NaN,New Zealand,12,35,2,5,138,50,0,...,2,2,1,0,0,0,0,2,1,0
12,NaN,NaN,USA,14,31,2,5,81,54,1,...,0,4,2,2,2,1,1,3,1,0
13,NaN,NaN,Spain,36,12,6,2,31,129,1,...,0,2,2,1,1,0,0,3,1,0
14,NaN,Average,NaN,29.5,17,4.5,2.7,50,85,2,...,1.7,2.2,1.5,2,2,0.7,0.5,2.7,1.5,0.2
15,NaN,Canada,South Africa,17,19,3,3,102,45,0,...,2,1,1,0,0,1,1,4,2,1
16,NaN,NaN,Argentina,12,14,2,2,105,97,1,...,0,3,2,0,0,4,4,4,2,0
17,NaN,NaN,France,35,7,5,1,56,178,2,...,1,1,1,2,2,2,2,3,2,0
18,NaN,NaN,Wales,31,14,5,2,51,90,1,...,3,1,1,0,0,1,1,2,2,1
19,NaN,NaN,Fiji,22,14,4,2,83,40,0,...,3,2,2,3,3,1,1,3,3,0
20,NaN,NaN,Samoa,17,19,3,3,91,66,0,...,1,0,0,2,2,1,1,4,4,0
21,NaN,Average,NaN,22.3,14.5,3.7,2.2,76,74,0.666667,...,1.7,1.3,1.2,1.2,1.2,1.7,1.7,3.3,2.5,0.3
22,NaN,England,Fiji,12,19,2,3,133,62,0,...,0,2,2,0,0,1,1,2,0,0
23,NaN,NaN,New Zealand,12,17,2,3,88,78,1,...,1,2,0,2,2,1,0,4,0,1
24,NaN,NaN,Scotland,12,7,2,1,117,221,1,...,2,2,2,1,1,1,1,3,0,0
25,NaN,NaN,Argentina,24,7,4,1,57,176,4,...,1,2,2,2,2,1,1,3,2,0
26,NaN,NaN,Uganda,36,0,6,0,42,0,5,...,2,0,0,2,2,0,0,2,0,0
27,NaN,Average,NaN,19.2,10,3.2,1.6,72,128,2.2,...,1.2,1.6,1.2,1.4,1.4,0.8,0.6,2.8,0.4,0.2
28,NaN,Fiji,USA,26,12,4,2,57,95,2,...,0,2,0,3,3,0,0,0,0,0
29,NaN,NaN,England,19,12,3,2,62,134,3,...,0,3,3,4,4,1,1,4,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,NaN,NaN,Scotland,0,45,0,7,0,34,0,...,0,6,2,0,0,1,0,4,2,0
92,NaN,NaN,England,0,36,0,6,0,42,0,...,0,6,4,3,3,0,0,3,2,0
93,NaN,Average,NaN,10.2,35.7,1.5,5.7,126,45,0.666667,...,0.2,5.5,2.2,1.8,1.8,0.3,0.2,2.8,1.5,0
94,NaN,USA,Fiji,12,26,2,4,95,57,1,...,2,4,4,2,2,2,1,3,2,0
95,NaN,NaN,France,29,12,5,2,58,68,5,...,3,2,1,0,0,2,2,0,0,0
96,NaN,NaN,Argentina,12,28,2,4,133,41,0,...,1,3,1,3,3,1,1,4,3,0
97,NaN,NaN,Spain,26,5,4,1,53,164,2,...,2,2,1,3,3,3,3,5,4,0
98,NaN,NaN,Australia,31,14,5,2,54,81,1,...,2,2,2,1,1,2,2,1,0,1
99,NaN,NaN,New Zealand,22,0,4,0,71,0,1,...,0,0,0,2,2,1,1,4,3,0
100,NaN,Average,NaN,22,14.2,3.7,2.2,68,77,1.66667,...,1.7,2.2,1.5,1.8,1.8,1.8,1.7,2.8,2,0.2
101,NaN,Wales,Australia,5,42,1,6,195,41,0,...,0,7,3,0,0,2,2,3,3,1
102,NaN,NaN,Russia,21,12,3,2,70,112,3,...,2,2,1,2,2,1,1,3,1,0
103,NaN,NaN,Canada,14,31,2,5,90,51,0,...,0,6,3,0,0,1,0,5,4,0
104,NaN,NaN,Samoa,17,12,3,2,76,118,2,...,1,3,3,3,3,0,0,6,2,0
105,NaN,NaN,Fiji,14,28,2,4,94,54,1,...,0,4,2,2,3,1,1,1,1,0
106,NaN,Average,NaN,14.2,25,2.2,3.8,91,62,1.2,...,0.6,4.4,2.4,1.4,1.6,1,0.8,3.6,2.2,0.2
107,NaN,Overall Average,NaN,19.0556,19.0556,3.04494,3.01111,86.1,86.1,1.53333,...,0.977778,2.72222,1.74444,1.45556,1.47778,1.04444,0.922222,3.16667,1.85556,0.2
108,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.47619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,...,NaN,NaN,NaN,NaN,,NaN,,NaN,NaN,NaN

In [17]:
# drop first column
df.drop(df.columns[0], axis=1, inplace=True)

# drop first row
df.drop([0])

# Drop unneccessary Average rows
df = df[df['Team'] != 'Average'] # Remove the 'Average' row
df = df[df['Team'] != 'Overall Average'] # Remove the 'Average' row

In [22]:
# New Column names to use
#newcols = ['Team1', 'Team2', 'Total PointsScored', 'Total PointsConceded', 'Total TriesScored', 
#'Total TriesConceded', 'Try Scoring Rate(1 every x secs)', 'Try Conceding Rate(1 every x secs)', 'Tries Scored Build-Up(No Ruck/Maul)', 'Tries Conceded Build-Up(No Ruck/Maul)', 'Opp22m Entries', 'Opp22m Entry Rate(1 every  secs)', 'Own22m Entries', 'Own22m Entry Rate(1 every x secs)', 'Tries Scoredper Opp22m Entry', 'Tries Concededper Own22m Entry', 'Possession Time(Own)', 'Possession Time(Opp)', 'Passes', 'Passing Rate(1 every x secs)', 'Rucks Attack', 'Rucking RateAttack (secs)', 'RucksDefence', '% Ruck SuccessOwn', 'Own RucksWon per Match', '% Ruck SuccessOpp', 'Opp RucksWon per Match', 'TurnoversReceived', 'TurnoversConceded', 'TurnoverDifferential', 'OwnContestable Restarts', 'Own ContestableRestarts Regained', 'OppContestable Restarts', 'Opp ContestableRestarts Received', 'Total ScrumsOwn Feed', 'Scrum SuccessOwn Feed', 'Total LineoutsOwn Throw', 'Lineout SuccessOwn Throw', 'Penalty/FKConceded', 'TRM PenaltyConceded', 'Cards']

,Team,Opposition,Total PointsScored,Total PointsConceded,Total TriesScored,Total TriesConceded,Try Scoring Rate(1 every x secs),Try Conceding Rate(1 every x secs),Tries Scored Build-Up(No Ruck/Maul),Tries Conceded Build-Up(No Ruck/Maul),...,Own ContestableRestarts Regained,OppContestable Restarts,Opp ContestableRestarts Received,Total ScrumsOwn Feed,Scrum SuccessOwn Feed,Total LineoutsOwn Throw,Lineout SuccessOwn Throw,Penalty/FKConceded,TRM PenaltyConceded,Cards
1,Argentina,New Zealand,14,38,2,6,108,36,1,4,...,1,0,0,0,0,2,1,1,0,0
2,Argentina,Canada,14,12,2,2,97,105,2,1,...,1,2,2,2,2,2,2,4,3,0
3,Argentina,USA,28,12,4,2,41,133,1,0,...,2,3,2,1,1,1,1,1,1,0
4,Argentina,Uganda,43,7,7,1,37,178,4,0,...,5,0,0,0,0,2,2,0,0,0
5,Argentina,England,7,24,1,4,176,57,0,4,...,0,4,3,3,3,2,0,0,0,0
6,Argentina,Scotland,19,14,3,2,60,95,1,1,...,1,3,3,2,2,2,2,4,0,0
8,Australia,Spain,26,7,4,1,58,189,3,1,...,1,2,1,4,4,2,2,5,4,0
9,Australia,Wales,42,5,6,1,41,195,3,0,...,4,1,1,2,2,1,0,3,2,1
10,Australia,Uganda,47,12,7,2,35,100,4,0,...,3,2,2,3,3,0,0,0,0,0
11,Australia,New Zealand,12,35,2,5,138,50,0,2,...,2,2,1,0,0,0,0,2,1,0
12,Australia,USA,14,31,2,5,81,54,1,1,...,0,4,2,2,2,1,1,3,1,0
13,Australia,Spain,36,12,6,2,31,129,1,2,...,0,2,2,1,1,0,0,3,1,0
15,Canada,South Africa,17,19,3,3,102,45,0,1,...,2,1,1,0,0,1,1,4,2,1
16,Canada,Argentina,12,14,2,2,105,97,1,2,...,0,3,2,0,0,4,4,4,2,0
17,Canada,France,35,7,5,1,56,178,2,0,...,1,1,1,2,2,2,2,3,2,0
18,Canada,Wales,31,14,5,2,51,90,1,0,...,3,1,1,0,0,1,1,2,2,1
19,Canada,Fiji,22,14,4,2,83,40,0,2,...,3,2,2,3,3,1,1,3,3,0
20,Canada,Samoa,17,19,3,3,91,66,0,1,...,1,0,0,2,2,1,1,4,4,0
22,England,Fiji,12,19,2,3,133,62,0,3,...,0,2,2,0,0,1,1,2,0,0
23,England,New Zealand,12,17,2,3,88,78,1,0,...,1,2,0,2,2,1,0,4,0,1
24,England,Scotland,12,7,2,1,117,221,1,1,...,2,2,2,1,1,1,1,3,0,0
25,England,Argentina,24,7,4,1,57,176,4,0,...,1,2,2,2,2,1,1,3,2,0
26,England,Uganda,36,0,6,0,42,0,5,0,...,2,0,0,2,2,0,0,2,0,0
28,Fiji,USA,26,12,4,2,57,95,2,1,...,0,2,0,3,3,0,0,0,0,0
29,Fiji,England,19,12,3,2,62,134,3,0,...,0,3,3,4,4,1,1,4,2,0
30,Fiji,South Africa,26,31,4,5,62,47,2,4,...,0,2,1,0,0,1,1,3,1,0
31,Fiji,Samoa,38,7,6,1,37,257,5,0,...,0,0,0,0,0,0,0,4,3,0
32,Fiji,Canada,14,22,2,4,40,83,2,0,...,0,5,2,0,0,0,0,5,4,0
33,Fiji,Wales,28,14,4,2,52,94,4,1,...,2,2,2,1,1,1,1,3,2,0
35,France,USA,12,29,2,5,67,58,0,5,...,1,4,1,0,0,0,0,5,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,Uganda,Kenya,14,24,2,4,83,65,1,4,...,1,5,0,2,2,0,0,2,1,0
88,Uganda,Russia,28,19,4,3,53,89,3,0,...,0,3,2,1,1,1,1,2,1,0
89,Uganda,Australia,12,47,2,7,100,35,0,4,...,0,5,2,1,1,0,0,2,1,0
90,Uganda,Argentina,7,43,1,7,178,37,0,4,...,0,8,3,4,4,0,0,4,2,0
91,Uganda,Scotland,0,45,0,7,0,34,0,3,...,0,6,2,0,0,1,0,4,2,0
92,Uganda,England,0,36,0,6,0,42,0,5,...,0,6,4,3,3,0,0,3,2,0
94,USA,Fiji,12,26,2,4,95,57,1,2,...,2,4,4,2,2,2,1,3,2,0
95,USA,France,29,12,5,2,58,68,5,0,...,3,2,1,0,0,2,2,0,0,0
96,USA,Argentina,12,28,2,4,133,41,0,1,...,1,3,1,3,3,1,1,4,3,0
97,USA,Spain,26,5,4,1,53,164,2,1,...,2,2,1,3,3,3,3,5,4,0
98,USA,Australia,31,14,5,2,54,81,1,1,...,2,2,2,1,1,2,2,1,0,1
99,USA,New Zealand,22,0,4,0,71,0,1,0,...,0,0,0,2,2,1,1,4,3,0
101,Wales,Australia,5,42,1,6,195,41,0,3,...,0,7,3,0,0,2,2,3,3,1
102,Wales,Russia,21,12,3,2,70,112,3,1,...,2,2,1,2,2,1,1,3,1,0
103,Wales,Canada,14,31,2,5,90,51,0,1,...,0,6,3,0,0,1,0,5,4,0
104,Wales,Samoa,17,12,3,2,76,118,2,2,...,1,3,3,3,3,0,0,6,2,0
105,Wales,Fiji,14,28,2,4,94,54,1,4,...,0,4,2,2,3,1,1,1,1,0
108,Wales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,Wales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,Wales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,Wales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.47619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,Wales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,Wales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,Wales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,Wales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,Wales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,Wales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,Wales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,Wales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,Wales,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,...,NaN,NaN,NaN,NaN,,NaN,,NaN,NaN,NaN

In [19]:
# pseudo: if Team = 'NaN', grab the value from the previous row using .fillna(method='ffill')
# forward fill
# Need to run on only 'Team' column
df[['Team']] = df[['Team']].fillna(method='ffill')

In [21]:
df

,Team,Opposition,Total PointsScored,Total PointsConceded,Total TriesScored,Total TriesConceded,Try Scoring Rate(1 every x secs),Try Conceding Rate(1 every x secs),Tries Scored Build-Up(No Ruck/Maul),Tries Conceded Build-Up(No Ruck/Maul),...,Own ContestableRestarts Regained,OppContestable Restarts,Opp ContestableRestarts Received,Total ScrumsOwn Feed,Scrum SuccessOwn Feed,Total LineoutsOwn Throw,Lineout SuccessOwn Throw,Penalty/FKConceded,TRM PenaltyConceded,Cards
0,Team,Opposition,Scored,Conceded,Scored,Conceded,(1 every '' secs),(1 every '' secs),(No Ruck/Maul),(No Ruck/Maul),...,Restarts Regained,Contestable Restarts,Restarts Received,Own Feed,Own Feed,Own Throw,Own Throw,Conceded,Conceded,Cards
1,Argentina,New Zealand,14,38,2,6,108,36,1,4,...,1,0,0,0,0,2,1,1,0,0
2,Argentina,Canada,14,12,2,2,97,105,2,1,...,1,2,2,2,2,2,2,4,3,0
3,Argentina,USA,28,12,4,2,41,133,1,0,...,2,3,2,1,1,1,1,1,1,0
4,Argentina,Uganda,43,7,7,1,37,178,4,0,...,5,0,0,0,0,2,2,0,0,0
5,Argentina,England,7,24,1,4,176,57,0,4,...,0,4,3,3,3,2,0,0,0,0
6,Argentina,Scotland,19,14,3,2,60,95,1,1,...,1,3,3,2,2,2,2,4,0,0
8,Australia,Spain,26,7,4,1,58,189,3,1,...,1,2,1,4,4,2,2,5,4,0
9,Australia,Wales,42,5,6,1,41,195,3,0,...,4,1,1,2,2,1,0,3,2,1
10,Australia,Uganda,47,12,7,2,35,100,4,0,...,3,2,2,3,3,0,0,0,0,0
11,Australia,New Zealand,12,35,2,5,138,50,0,2,...,2,2,1,0,0,0,0,2,1,0
12,Australia,USA,14,31,2,5,81,54,1,1,...,0,4,2,2,2,1,1,3,1,0
13,Australia,Spain,36,12,6,2,31,129,1,2,...,0,2,2,1,1,0,0,3,1,0
15,Canada,South Africa,17,19,3,3,102,45,0,1,...,2,1,1,0,0,1,1,4,2,1
16,Canada,Argentina,12,14,2,2,105,97,1,2,...,0,3,2,0,0,4,4,4,2,0
17,Canada,France,35,7,5,1,56,178,2,0,...,1,1,1,2,2,2,2,3,2,0
18,Canada,Wales,31,14,5,2,51,90,1,0,...,3,1,1,0,0,1,1,2,2,1
19,Canada,Fiji,22,14,4,2,83,40,0,2,...,3,2,2,3,3,1,1,3,3,0
20,Canada,Samoa,17,19,3,3,91,66,0,1,...,1,0,0,2,2,1,1,4,4,0
22,England,Fiji,12,19,2,3,133,62,0,3,...,0,2,2,0,0,1,1,2,0,0
23,England,New Zealand,12,17,2,3,88,78,1,0,...,1,2,0,2,2,1,0,4,0,1
24,England,Scotland,12,7,2,1,117,221,1,1,...,2,2,2,1,1,1,1,3,0,0
25,England,Argentina,24,7,4,1,57,176,4,0,...,1,2,2,2,2,1,1,3,2,0
26,England,Uganda,36,0,6,0,42,0,5,0,...,2,0,0,2,2,0,0,2,0,0
28,Fiji,USA,26,12,4,2,57,95,2,1,...,0,2,0,3,3,0,0,0,0,0
29,Fiji,England,19,12,3,2,62,134,3,0,...,0,3,3,4,4,1,1,4,2,0
30,Fiji,South Africa,26,31,4,5,62,47,2,4,...,0,2,1,0,0,1,1,3,1,0
31,Fiji,Samoa,38,7,6,1,37,257,5,0,...,0,0,0,0,0,0,0,4,3,0
32,Fiji,Canada,14,22,2,4,40,83,2,0,...,0,5,2,0,0,0,0,5,4,0
33,Fiji,Wales,28,14,4,2,52,94,4,1,...,2,2,2,1,1,1,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,Uganda,Kenya,14,24,2,4,83,65,1,4,...,1,5,0,2,2,0,0,2,1,0
88,Uganda,Russia,28,19,4,3,53,89,3,0,...,0,3,2,1,1,1,1,2,1,0
89,Uganda,Australia,12,47,2,7,100,35,0,4,...,0,5,2,1,1,0,0,2,1,0
90,Uganda,Argentina,7,43,1,7,178,37,0,4,...,0,8,3,4,4,0,0,4,2,0
91,Uganda,Scotland,0,45,0,7,0,34,0,3,...,0,6,2,0,0,1,0,4,2,0
92,Uganda,England,0,36,0,6,0,42,0,5,...,0,6,4,3,3,0,0,3,2,0
94,USA,Fiji,12,26,2,4,95,57,1,2,...,2,4,4,2,2,2,1,3,2,0
95,USA,France,29,12,5,2,58,68,5,0,...,3,2,1,0,0,2,2,0,0,0
96,USA,Argentina,12,28,2,4,133,41,0,1,...,1,3,1,3,3,1,1,4,3,0
97,USA,Spain,26,5,4,1,53,164,2,1,...,2,2,1,3,3,3,3,5,4,0
98,USA,Australia,31,14,5,2,54,81,1,1,...,2,2,2,1,1,2,2,1,0,1
99,USA,New Zealand,22,0,4,0,71,0,1,0,...,0,0,0,2,2,1,1,4,3,0
101,Wales,Australia,5,42,1,6,195,41,0,3,...,0,7,3,0,0,2,2,3,3,1
102,Wales,Russia,21,12,3,2,70,112,3,1,...,2,2,1,2,2,1,1,3,1,0
103,Wales,Canada,14,31,2,5,90,51,0,1,...,0,6,3,0,0,1,0,5,4,0
104,Wales,Samoa,17,12,3,2,76,118,2,2,...,1,3,3,3,3,0,0,6,2,0
105,Wales,Fiji,14,28,2,4,94,54,1,4,...,0,4,2,2,3,1,1,1,1,0
108,Wales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,Wales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,Wales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,Wales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.47619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,Wales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,Wales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,Wales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,Wales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,Wales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,Wales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,Wales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,Wales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,Wales,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,...,NaN,NaN,NaN,NaN,,NaN,,NaN,NaN,NaN

In [ ]:
# Fill remaining NaNs with 0
# df[2:31] = df[2:31].fillna(value=0.0)

In [ ]:
df

### Column labels ###

In [36]:
# change col names.  Should 'TurnoversReceived' be 'T-Overs Won' + 'General Play T/Overs' ??
# Get tournament name from filename
newcols = ['Possession Time(Own)':'Possession Time', 'Total PointsScored':'Scores', 'Total TriesScored':'Tries', 'Conversions', 'Passes',
       'Rucks Attack':'Tackle_Ruck_Mauls', 'Own RucksWon per Match':'Retained', 'TurnoversReceived':'T-Overs Won', 'General Play T/Overs',
       'Total LineoutsOwn Throw':'Lineouts', 'Lineout SuccessOwn Throw':'Own Won', 'Own Lost', 'Total ScrumsOwn Feed':'Scrums', 'Scrum SuccessOwn Feed':'Own Won', 'Own Lost',
       'OwnContestable Restarts':'Short', 'Own ContestableRestarts Regained':'Regained', 'Penalty/FKConceded':'Pens_Frees Against', 'TRM PenaltyConceded''Ruck_Maul',
       'Yellow_Red Cards', 'Team', 'Date', 'Tournament', 'Match']

SyntaxError: invalid syntax (<ipython-input-36-489f9d0f94bf>, line 2)

In [35]:
# Select only matches with the USA playing
usadf = df.loc[(df['Team'] == 'USA') | (df['Opposition'] == 'USA')]
usadf.columns

Index(['Team', 'Opposition', 'Total PointsScored', 'Total PointsConceded',
       'Total TriesScored', 'Total TriesConceded',
       'Try Scoring Rate(1 every x secs)',
       'Try Conceding Rate(1 every x secs)',
       'Tries Scored Build-Up(No Ruck/Maul)',
       'Tries Conceded Build-Up(No Ruck/Maul)', 'Opp22m Entries',
       'Opp22m Entry Rate(1 every  secs)', 'Own22m Entries',
       'Own22m Entry Rate(1 every x secs)', 'Tries Scoredper Opp22m Entry',
       'Tries Concededper Own22m Entry', 'Possession Time(Own)',
       'Possession Time(Opp)', 'Passes', 'Passing Rate(1 every x secs)',
       'Rucks Attack', 'Rucking RateAttack (secs)', 'RucksDefence',
       '% Ruck SuccessOwn', 'Own RucksWon per Match', '% Ruck SuccessOpp',
       'Opp RucksWon per Match', 'TurnoversReceived', 'TurnoversConceded',
       'TurnoverDifferential', 'OwnContestable Restarts',
       'Own ContestableRestarts Regained', 'OppContestable Restarts',
       'Opp ContestableRestarts Received', 'Total ScrumsOwn Feed',
       'Scrum SuccessOwn Feed', 'Total LineoutsOwn Throw',
       'Lineout SuccessOwn Throw', 'Penalty/FKConceded', 'TRM PenaltyConceded',
       'Cards'],
      dtype='object')

## Rename columns to match other dataframe, then drop all other columns

In [28]:
# newcols = ['Team', 'Date', 'Possession Time', 'Possessions', 'Avg Possession Time', 'Scores', 'Tries', 'Conversions', 'Tries Conceded', 'Points Conceded', 'Passes', 'Tackle_Ruck_Mauls', 'Retained', 'Lost', 'T-Overs Won', 'Tackle Only-Defence', 'Mauls', 'Kicks', 'General Play T/Overs', 'Lineouts', 'Own Won', 'Own Lost', 'Scrums', 'Own Won', 'Own Lost', 'Restarts', 'Long', 'Short', 'Regained', 'Errors', 'Pens_Frees Against', 'Ruck_Maul', 'Set Piece', 'General Play', 'Foul Play', 'Yellow_Red Cards']

In [ ]:
# MUST BE LAST OPERATION
# After all legit NaNs are replaced, Drop all rows that contain NaN
df.dropna(axis=0, inplace=True)

# reset index
df.reset_index(drop=True)

In [32]:
# write dataframe to CSV file
usadf.to_csv(path_or_buf='../data/worldrugby_game_analysis_all.csv')

In [ ]:
# Concantenate to append rows
# https://pandas.pydata.org/pandas-docs/stable/merging.html

## Sample Queries ##

In [25]:
# Select row by Team
# df.loc[df['column_name'] == some_value]
#df.loc[(df['Team'] == 'USA') & (df['Scored'] >= 10)]
df.loc[(df['Team'] == 'USA') | (df['Opposition'] == 'USA')]
# Select teams with match points scored > or = 20
#df.loc[df['Scored'] >= 20]

,Team,Opposition,Total PointsScored,Total PointsConceded,Total TriesScored,Total TriesConceded,Try Scoring Rate(1 every x secs),Try Conceding Rate(1 every x secs),Tries Scored Build-Up(No Ruck/Maul),Tries Conceded Build-Up(No Ruck/Maul),...,Own ContestableRestarts Regained,OppContestable Restarts,Opp ContestableRestarts Received,Total ScrumsOwn Feed,Scrum SuccessOwn Feed,Total LineoutsOwn Throw,Lineout SuccessOwn Throw,Penalty/FKConceded,TRM PenaltyConceded,Cards
3,Argentina,USA,28,12,4,2,41,133,1,0,...,2,3,2,1,1,1,1,1,1,0
12,Australia,USA,14,31,2,5,81,54,1,1,...,0,4,2,2,2,1,1,3,1,0
28,Fiji,USA,26,12,4,2,57,95,2,1,...,0,2,0,3,3,0,0,0,0,0
35,France,USA,12,29,2,5,67,58,0,5,...,1,4,1,0,0,0,0,5,2,2
53,New Zealand,USA,0,22,0,4,0,71,0,1,...,0,4,4,0,0,0,0,4,3,1
83,Spain,USA,5,26,1,4,164,53,1,2,...,1,4,2,3,3,1,1,3,1,1
94,USA,Fiji,12,26,2,4,95,57,1,2,...,2,4,4,2,2,2,1,3,2,0
95,USA,France,29,12,5,2,58,68,5,0,...,3,2,1,0,0,2,2,0,0,0
96,USA,Argentina,12,28,2,4,133,41,0,1,...,1,3,1,3,3,1,1,4,3,0
97,USA,Spain,26,5,4,1,53,164,2,1,...,2,2,1,3,3,3,3,5,4,0
98,USA,Australia,31,14,5,2,54,81,1,1,...,2,2,2,1,1,2,2,1,0,1
99,USA,New Zealand,22,0,4,0,71,0,1,0,...,0,0,0,2,2,1,1,4,3,0